version: '3.7'

services: 
    backend:
        build:
            context: backend/.
            args:
                - NODE_ENV=development
        image: backend_nlw
        container_name: backend_nlw
        ports: 
            - 3333:3000
            - 9922:9229
        volumes: 
            - ./backend:/usr/app
        command: npm run dev
    
    frontend:
        build: 
            context: frontend/.
            args: 
                - NODE_ENV=development
        image: frontend_nlw
        container_name: frontend_nlw
        ports:
            - 3006:3000
        volumes: 
            - ./frontend:/usr/app
        command: npm run start
        stdin_open: true

    mobile:
        build: 
            context: mobile/.
            args:
                - NODE_ENV=development
        image: mobile_nlw
        container_name: mobile_nlw
        ports:
            - 19000:19000
            - 19001:19001
            - 19002:19002
        volumes: 
            - ./mobile:/usr/app
        command: npm run start
        environment:
            - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
            - ADB_IP=192.168.1.1
            - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.105

