version: '3.7'

services: 
    backend:
        build:
            context: backend/.
            args:
                - NODE_ENV=development
        image: backend_nlw
        container_name: backend_nlw
        ports: 
            - 3333:3000
            - 9922:9229
        volumes: 
            - ./backend:/usr/app
            - /usr/app/node_modules
        command: npm run dev
