version: '3.7'

services: 
    backend:
        build:
            context: backend/.
            args:
                - NODE_ENV=development
        image: backend_nlw
        container_name: backend_nlw
        ports: 
            - 3333:3000
            - 9922:9229
        volumes: 
            - ./backend:/usr/app
        command: npm run dev
    
    frontend:
        build: 
            context: frontend/.
            args: 
                - NODE_ENV=development
        image: frontend_nlw
        container_name: frontend_nlw
        ports:
            - 3006:3000
        volumes: 
            - ./frontend:/usr/app
        command: npm run start
        stdin_open: true
